version: '3.3'
services:

  db:
    image: postgres    server_name test-site.ddns.net;
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data
    container_name: db
    env_file:
      - .env

  backend:
    image: 0z0nize/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    container_name: backend
    env_file:
      - .env

  frontend:
    image: 0z0nize/foodgram_frontend:latest
    volumes:
      - frontend_value:/app/result_build/build
    depends_on:
      - db
    container_name: frontend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - frontend_value:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    container_name: nginx
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    # command: certonly --webroot --webroot-path=/var/www/html --email ozonize@mail.ru --agree-tos --no-eff-email -d test-site.ddns.net

volumes:
  db_value:
  static_value:
  media_value:  
  www-html:
  etc-letsencrypt:
  frontend_value:
  