version: '3.3'
services:

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: 0z0nize/foodgram_backend:latest
    container_name: backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: 0z0nize/foodgram_frontend:latest
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
#       - web-root:/var/html
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
    depends_on:
      - backend

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#       - web-root:/var/html
#     depends_on:
#       - nginx
#    command: certonly --webroot --webroot-path=/var/html --email ozonize@mail.ru --agree-tos --no-eff-email --staging -d 50.ddns.net
#    command: certonly --webroot --webroot-path=/var/html --email ozonize@mail.ru --agree-tos --no-eff-email --force-renewal -d 50.ddns.net

volumes:
  db_value:
  static_value:
  media_value:
#   web-root:
#   certbot-etc:
#   certbot-var:
