# Generated by Django 3.2 on 2023-06-04 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message='Значение меньше минимального'
                    )
                ],
                verbose_name='Кол-во ингредиента',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message='Значение меньше минимального'
                    )
                ],
                verbose_name='Время приготовления',
            ),
        ),
    ]
